Repository Workiva/eva-catalog, pull requests merged in 2019-07, with the labels that each got.

#11 Use Dockerhub Images
  docker/docker-compose.yml
  scripts/run_service.sh
Labels: Merge Requirements Met

#12 RM-53507 Release eva-catalog v2.0.3
  client.alpha/project.clj
  common.alpha/project.clj
  project.clj
  server.alpha/project.clj
Labels: Merge Requirements Met, RM Ready

#13 Build uberjar.
  .circleci/config.yml
Labels: Merge Requirements Unmet, RM Ready

#14 RM-54675 Release eva-catalog v2.0.4
  client.alpha/project.clj
  common.alpha/project.clj
  project.clj
  server.alpha/project.clj
Labels: Merge Requirements Met, RM Ready

#15 Use the uberjar
  .circleci/config.yml
  catalog.Dockerfile
Labels: Merge Requirements Met, RM Ready

#16 RM-54768 Release eva-catalog v2.0.5
  client.alpha/project.clj
  common.alpha/project.clj
  project.clj
  server.alpha/project.clj
Labels: Merge Requirements Met, RM Ready
